# https://docs.github.com/en/actions

name: "Merge"

on: # yamllint disable-line rule:truthy
    workflow_run:
        types:
            - "completed"
        workflows:
            - "Integrate"

jobs:
    merge:
        name: "Merge"

        runs-on: "ubuntu-latest"

        timeout-minutes: 5

        if: >
            github.event.workflow_run.event == 'pull_request' &&
            github.event.workflow_run.conclusion == 'success' &&
            github.actor == 'dependabot[bot]' && (
              startsWith(github.event.workflow_run.head_commit.message, 'composer(deps-dev)') ||
              startsWith(github.event.workflow_run.head_commit.message, 'github-actions(deps)')
            )

        steps:
            - name: "Request review from @faustbrian"
              uses: "basecodeoy/.github/actions/github/pull-request/request-review@1.0.2"
              with:
                  github-token: "${{ secrets.PAT }}"
                  reviewer: "faustbrian"

            - name: "Assign @faustbrian"
              uses: "basecodeoy/.github/actions/github/pull-request/add-assignee@1.0.2"
              with:
                  assignee: "faustbrian"
                  github-token: "${{ secrets.PAT }}"

            - name: "Approve pull request"
              uses: "basecodeoy/.github/actions/github/pull-request/approve@1.0.2"
              with:
                  github-token: "${{ secrets.PAT }}"

            - name: "Merge pull request"
              uses: "basecodeoy/.github/actions/github/pull-request/merge@1.0.2"
              with:
                  github-token: "${{ secrets.PAT }}"
